# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='classification',
            field=models.ForeignKey(help_text='An organization category, e.g. committee', on_delete=django.db.models.deletion.PROTECT, to='decisions.OrganizationClass'),
        ),
    ]
