# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_add_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='date',
            field=models.DateTimeField(help_text='Date and time this decision was made at', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='The time at which the event ends', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='The time at which the event starts'),
        ),
    ]
