# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_add_event_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which the resource was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='The time at which the resource was updated')),
                ('origin_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('path', models.CharField(db_index=True, max_length=2000)),
                ('last_import_mtime', models.CharField(max_length=100)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='decisions.DataSource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='action',
            name='event',
        ),
        migrations.AddField(
            model_name='action',
            name='date',
            field=models.DateTimeField(help_text='Date and time this decision was made at', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='The time at which the event ends', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='The time at which the event starts'),
        ),
        migrations.AlterUniqueTogether(
            name='importedfile',
            unique_together=set([('data_source', 'origin_id')]),
        ),
    ]
