# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0004_date_to_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which the resource was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='The time at which the resource was updated')),
                ('path', models.CharField(db_index=True, max_length=2000)),
                ('imported_version', models.CharField(max_length=100)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='decisions.DataSource')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='importedfile',
            unique_together=set([('data_source', 'path')]),
        ),
    ]
